[env]
NEOCITIES_MISE_ACTIVE = 'true'

[settings]
env_file = '.env'

[tools]
ruby = { version = "3.4.6" }

[tasks]
'push' = { run = 'neocities push --prune src/' }
'info' = { run = 'neocities info' }
'pull' = { run = 'neocities pull' }
'browse' = { run = 'open https://daveio.neocities.org' }
