import json

# Comprehensive terminal comparison data
terminals_data = {
    "Alacritty": {
        "description": "GPU-accelerated, minimal, Rust-based",
        "performance": 95,
        "features": 40,
        "ease_of_use": 70,
        "price": "Free",
        "platforms": ["Windows", "macOS", "Linux", "BSD"],
        "gpu_accelerated": True,
        "native_tabs": False,
        "ai_features": False,
        "ssh_built_in": False,
        "themes": 20,
        "startup_ms": 75,
        "idle_cpu": "5-8%",
        "scrolling": "Excellent",
        "language": "Rust",
        "open_source": True,
        "key_features": ["GPU rendering", "Fast startup", "Ligatures", "True color"],
        "best_for": ["Raw speed", "Minimal workflows", "tmux users"],
        "license": "Apache 2.0",
    },
    "Ghostty": {
        "description": "Modern GPU-accelerated, Zig-based, balanced",
        "performance": 92,
        "features": 75,
        "ease_of_use": 85,
        "price": "Free",
        "platforms": ["macOS", "Linux"],
        "gpu_accelerated": True,
        "native_tabs": True,
        "ai_features": False,
        "ssh_built_in": False,
        "themes": 100,
        "startup_ms": 150,
        "idle_cpu": "6-8%",
        "scrolling": "Excellent",
        "language": "Zig",
        "open_source": True,
        "key_features": [
            "Native tabs/splits",
            "100+ themes",
            "Inspector tool",
            "Shell integration",
        ],
        "best_for": ["Speed + features", "Modern developers", "Native UX"],
        "license": "MIT",
    },
    "Hyper": {
        "description": "Electron-based, aesthetic-focused, extensible",
        "performance": 35,
        "features": 85,
        "ease_of_use": 80,
        "price": "Free",
        "platforms": ["Windows", "macOS", "Linux"],
        "gpu_accelerated": False,
        "native_tabs": False,
        "ai_features": False,
        "ssh_built_in": False,
        "themes": 100,
        "startup_ms": 2000,
        "idle_cpu": "15-20%",
        "scrolling": "Poor",
        "language": "JavaScript",
        "open_source": True,
        "key_features": ["Beautiful UI", "Plugin ecosystem", "JS customization"],
        "best_for": ["Aesthetics", "Plugin enthusiasts"],
        "license": "MIT",
    },
    "iTerm2": {
        "description": "Feature-rich macOS standard",
        "performance": 70,
        "features": 95,
        "ease_of_use": 75,
        "price": "Free",
        "platforms": ["macOS"],
        "gpu_accelerated": True,
        "native_tabs": True,
        "ai_features": False,
        "ssh_built_in": False,
        "themes": 50,
        "startup_ms": 500,
        "idle_cpu": "10-20%",
        "scrolling": "Good",
        "language": "Objective-C",
        "open_source": False,
        "key_features": [
            "Split panes",
            "Instant replay",
            "Hotkey window",
            "Advanced search",
        ],
        "best_for": ["macOS users", "Feature power users"],
        "license": "Proprietary",
    },
    "Kitty": {
        "description": "GPU-accelerated, feature-rich, keyboard-centric",
        "performance": 90,
        "features": 85,
        "ease_of_use": 70,
        "price": "Free",
        "platforms": ["Linux", "macOS", "BSD"],
        "gpu_accelerated": True,
        "native_tabs": True,
        "ai_features": False,
        "ssh_built_in": False,
        "themes": 60,
        "startup_ms": 80,
        "idle_cpu": "6-8%",
        "scrolling": "Excellent",
        "language": "Python + C",
        "open_source": True,
        "key_features": [
            "Kitty graphics protocol",
            "SIMD optimization",
            "Kittens plugins",
            "Ligatures",
        ],
        "best_for": ["Linux users", "Graphics needs", "Performance"],
        "license": "GPL 3.0",
    },
    "Tabby": {
        "description": "Feature-rich SSH client terminal, Electron-based",
        "performance": 50,
        "features": 95,
        "ease_of_use": 80,
        "price": "Free",
        "platforms": ["Windows", "macOS", "Linux"],
        "gpu_accelerated": False,
        "native_tabs": True,
        "ai_features": False,
        "ssh_built_in": True,
        "themes": 25,
        "startup_ms": 2500,
        "idle_cpu": "High",
        "scrolling": "Fair",
        "language": "TypeScript",
        "open_source": True,
        "key_features": ["SSH client", "Serial support", "SFTP integration", "Plugins"],
        "best_for": ["SSH management", "Multi-protocol", "Cross-platform"],
        "license": "Apache 2.0",
    },
    "Warp": {
        "description": "AI-powered, modern, collaborative terminal",
        "performance": 85,
        "features": 90,
        "ease_of_use": 90,
        "price": "Free (with premium)",
        "platforms": ["macOS", "Linux"],
        "gpu_accelerated": True,
        "native_tabs": True,
        "ai_features": True,
        "ssh_built_in": False,
        "themes": 40,
        "startup_ms": 150,
        "idle_cpu": "Efficient",
        "scrolling": "Good",
        "language": "Rust",
        "open_source": False,
        "key_features": [
            "AI suggestions",
            "Block interface",
            "Collaboration",
            "Agent mode",
        ],
        "best_for": ["AI-powered workflows", "Team collaboration", "Modern devs"],
        "license": "Proprietary",
    },
    "Wave": {
        "description": "AI-native, graphical, open-source terminal",
        "performance": 80,
        "features": 88,
        "ease_of_use": 85,
        "price": "Free",
        "platforms": ["macOS", "Linux", "Windows"],
        "gpu_accelerated": False,
        "native_tabs": True,
        "ai_features": True,
        "ssh_built_in": False,
        "themes": 30,
        "startup_ms": 200,
        "idle_cpu": "Efficient",
        "scrolling": "Good",
        "language": "Modern",
        "open_source": True,
        "key_features": [
            "Built-in editor",
            "AI chat",
            "File preview",
            "Block interface",
        ],
        "best_for": ["Graphical workflows", "File editing", "DevOps"],
        "license": "Apache 2.0",
    },
    "WezTerm": {
        "description": "Rust-based, Lua-configurable, powerful",
        "performance": 85,
        "features": 88,
        "ease_of_use": 65,
        "price": "Free",
        "platforms": ["Windows", "macOS", "Linux"],
        "gpu_accelerated": True,
        "native_tabs": True,
        "ai_features": False,
        "ssh_built_in": False,
        "themes": 50,
        "startup_ms": 200,
        "idle_cpu": "Efficient",
        "scrolling": "Good",
        "language": "Rust",
        "open_source": True,
        "key_features": [
            "Lua configuration",
            "Multiplexing",
            "Status bar",
            "Image support",
        ],
        "best_for": ["Lua scripting", "Neovim users", "Cross-platform"],
        "license": "MIT",
    },
    "WindTerm": {
        "description": "Professional multi-protocol terminal",
        "performance": 85,
        "features": 92,
        "ease_of_use": 75,
        "price": "Free",
        "platforms": ["Windows", "macOS", "Linux"],
        "gpu_accelerated": False,
        "native_tabs": True,
        "ai_features": False,
        "ssh_built_in": True,
        "themes": 40,
        "startup_ms": 300,
        "idle_cpu": "Efficient",
        "scrolling": "Good",
        "language": "Native",
        "open_source": True,
        "key_features": [
            "SSH/Telnet/Serial",
            "Session mgmt",
            "SFTP client",
            "Port forwarding",
        ],
        "best_for": ["SysAdmins", "Network engineers", "Multi-protocol"],
        "license": "MIT",
    },
    "ZOC": {
        "description": "Professional, legacy-rich terminal",
        "performance": 80,
        "features": 96,
        "ease_of_use": 70,
        "price": "$80 (commercial)",
        "platforms": ["Windows", "macOS"],
        "gpu_accelerated": False,
        "native_tabs": True,
        "ai_features": False,
        "ssh_built_in": True,
        "themes": 50,
        "startup_ms": 400,
        "idle_cpu": "Efficient",
        "scrolling": "Good",
        "language": "Native",
        "open_source": False,
        "key_features": [
            "15+ terminal emus",
            "Mainframe support",
            "REXX scripting",
            "Enterprise features",
        ],
        "best_for": ["Enterprise", "Legacy systems", "Mainframes"],
        "license": "Commercial",
    },
}

# Save as JSON for the app
with open("terminals_data.json", "w") as f:
    json.dump(terminals_data, f, indent=2)

print("✅ Terminal data compiled successfully")
print(f"Total terminals: {len(terminals_data)}")
for name, data in terminals_data.items():
    print(f"  - {name}: {data['description']}")
